import type { AppData } from "./types";

const DAY = 86400000;
const now = Date.now();

function d(offsetDays: number) {
  return now + offsetDays * DAY;
}

export function createSeed(): AppData {
  return {
    version: 1,
    profile: {
      name: "Toyyibah Nnnam",
      email: "toyyibahnnam@gmail.com",
      role: "Premium User",
      business: "Toyyibah Studio",
      avatarColor: "linear-gradient(135deg,#6366f1,#a855f7)",
    },
    clients: [
      {
        id: "c1",
        name: "Amelia Stone",
        company: "Acme Co.",
        email: "amelia@acme.co",
        phone: "+1 (415) 555-0132",
        avatarColor: "linear-gradient(135deg,#6366f1,#8b5cf6)",
        initials: "A",
        status: "active",
        priority: "high",
        tags: ["Retainer", "Design"],
        website: "acme.co",
        location: "San Francisco, US",
        notes: "Long-term retainer client. Prefers Friday check-ins.",
        createdAt: d(-120),
      },
      {
        id: "c2",
        name: "Marco Reyes",
        company: "Pixel Perfect",
        email: "marco@pixelperfect.io",
        phone: "+1 (212) 555-0177",
        avatarColor: "linear-gradient(135deg,#a855f7,#ec4899)",
        initials: "P",
        status: "active",
        priority: "medium",
        tags: ["Web", "Branding"],
        website: "pixelperfect.io",
        location: "New York, US",
        notes: "Fast-moving startup. Needs weekly progress reports.",
        createdAt: d(-90),
      },
      {
        id: "c3",
        name: "Sofia Lindqvist",
        company: "Vercel",
        email: "sofia@vercel.com",
        phone: "+46 8 555 0199",
        avatarColor: "linear-gradient(135deg,#0f172a,#334155)",
        initials: "V",
        status: "completed",
        priority: "low",
        tags: ["Consulting"],
        website: "vercel.com",
        location: "Stockholm, SE",
        notes: "UI redesign delivered. Potential future work in Q3.",
        createdAt: d(-200),
      },
      {
        id: "c4",
        name: "Daniel Osei",
        company: "Atlas Corp",
        email: "daniel@atlascorp.com",
        phone: "+44 20 5550 0143",
        avatarColor: "linear-gradient(135deg,#10b981,#22d3ee)",
        initials: "A",
        status: "active",
        priority: "high",
        tags: ["Enterprise", "Dev"],
        website: "atlascorp.com",
        location: "London, UK",
        notes: "Enterprise account. Multi-phase engagement.",
        createdAt: d(-45),
      },
      {
        id: "c5",
        name: "Hana Kim",
        company: "Stripe",
        email: "hana@stripe.com",
        phone: "+1 (628) 555-0110",
        avatarColor: "linear-gradient(135deg,#635bff,#8b5cf6)",
        initials: "S",
        status: "overdue",
        priority: "high",
        tags: ["Fintech", "API"],
        website: "stripe.com",
        location: "Dublin, IE",
        notes: "API integration project. Invoice overdue — follow up.",
        createdAt: d(-70),
      },
    ],
    leads: [
      { id: "l1", name: "Northwind Labs", company: "Northwind", stage: "new", value: 8000, progress: 15, source: "Referral", createdAt: d(-4) },
      { id: "l2", name: "Bright Media", company: "Bright", stage: "new", value: 5200, progress: 10, source: "Website", createdAt: d(-2) },
      { id: "l3", name: "Lumen Health", company: "Lumen", stage: "contacted", value: 12000, progress: 40, source: "LinkedIn", createdAt: d(-9) },
      { id: "l4", name: "Cascade Studio", company: "Cascade", stage: "proposal", value: 9500, progress: 60, source: "Referral", createdAt: d(-14) },
      { id: "l5", name: "Orbit Finance", company: "Orbit", stage: "negotiation", value: 18000, progress: 80, source: "Cold email", createdAt: d(-20) },
      { id: "l6", name: "Vela Design", company: "Vela", stage: "won", value: 14000, progress: 100, source: "Referral", createdAt: d(-30) },
      { id: "l7", name: "Peak Ventures", company: "Peak", stage: "lost", value: 6000, progress: 25, source: "Website", createdAt: d(-40) },
    ],
    quotes: [
      { id: "q1", number: "QT-1042", clientId: "c4", status: "sent", createdAt: d(-6), validUntil: d(14), items: [ { id: "qi1", label: "Discovery & Strategy", qty: 1, price: 2500 }, { id: "qi2", label: "UI/UX Design", qty: 1, price: 4800 } ] },
      { id: "q2", number: "QT-1043", clientId: "c2", status: "viewed", createdAt: d(-3), validUntil: d(20), items: [ { id: "qi3", label: "Website Redesign", qty: 1, price: 6200 } ] },
      { id: "q3", number: "QT-1044", clientId: "c1", status: "accepted", createdAt: d(-12), validUntil: d(2), items: [ { id: "qi4", label: "Monthly Retainer", qty: 3, price: 1800 } ] },
      { id: "q4", number: "QT-1045", clientId: "c5", status: "draft", createdAt: d(-1), validUntil: d(30), items: [ { id: "qi5", label: "API Integration", qty: 1, price: 7500 } ] },
      { id: "q5", number: "QT-1041", clientId: "c3", status: "rejected", createdAt: d(-25), validUntil: d(-5), items: [ { id: "qi6", label: "Brand Refresh", qty: 1, price: 3200 } ] },
    ],
    projects: [
      { id: "p1", name: "Vercel UI Redesign", clientId: "c3", status: "completed", priority: "medium", progress: 100, budget: 12000, deadline: d(-10), createdAt: d(-120), milestones: [ { id: "m1", title: "Wireframes", done: true }, { id: "m2", title: "Visual design", done: true }, { id: "m3", title: "Handoff", done: true } ] },
      { id: "p2", name: "Stripe API Integration", clientId: "c5", status: "active", priority: "high", progress: 65, budget: 18000, deadline: d(20), createdAt: d(-40), milestones: [ { id: "m4", title: "Auth flow", done: true }, { id: "m5", title: "Webhooks", done: true }, { id: "m6", title: "Dashboard", done: false }, { id: "m7", title: "QA & launch", done: false } ] },
      { id: "p3", name: "Acme Brand System", clientId: "c1", status: "active", priority: "high", progress: 45, budget: 22000, deadline: d(35), createdAt: d(-30), milestones: [ { id: "m8", title: "Logo suite", done: true }, { id: "m9", title: "Guidelines", done: false }, { id: "m10", title: "Templates", done: false } ] },
      { id: "p4", name: "Atlas Marketing Site", clientId: "c4", status: "active", priority: "medium", progress: 30, budget: 15000, deadline: d(50), createdAt: d(-20), milestones: [ { id: "m11", title: "Content", done: true }, { id: "m12", title: "Build", done: false } ] },
      { id: "p5", name: "Pixel Perfect Landing", clientId: "c2", status: "on-hold", priority: "low", progress: 20, budget: 6000, deadline: d(60), createdAt: d(-15), milestones: [ { id: "m13", title: "Copy", done: false } ] },
    ],
    invoices: [
      { id: "i1", number: "INV-102", clientId: "c4", amount: 5000, status: "paid", issuedAt: d(-40), dueAt: d(-10), paidAt: d(-12) },
      { id: "i2", number: "INV-103", clientId: "c1", amount: 5400, status: "paid", issuedAt: d(-35), dueAt: d(-5), paidAt: d(-6) },
      { id: "i3", number: "INV-130", clientId: "c5", amount: 4200, status: "overdue", issuedAt: d(-50), dueAt: d(-8) },
      { id: "i4", number: "INV-171", clientId: "c3", amount: 3000, status: "draft", issuedAt: d(-2), dueAt: d(28) },
      { id: "i5", number: "INV-172", clientId: "c2", amount: 3500, status: "pending", issuedAt: d(-6), dueAt: d(9) },
      { id: "i6", number: "INV-173", clientId: "c4", amount: 6800, status: "paid", issuedAt: d(-20), dueAt: d(2), paidAt: d(-1) },
      { id: "i7", number: "INV-174", clientId: "c1", amount: 1800, status: "pending", issuedAt: d(-3), dueAt: d(12) },
    ],
    notes: [
      { id: "n1", title: "Kickoff — Stripe API", clientId: "c5", body: "Discussed authentication approach and webhook events. Client wants a dedicated payments dashboard with real-time updates.", followUpAt: d(3), attachments: ["kickoff-deck.pdf", "scope.docx"], actionItems: [ { id: "a1", text: "Send updated timeline", done: false }, { id: "a2", text: "Share Figma prototype", done: true } ], createdAt: d(-8) },
      { id: "n2", title: "Acme brand review", clientId: "c1", body: "Reviewed logo directions. Client leaning toward the geometric mark. Needs mockups on merch.", followUpAt: d(5), attachments: ["logo-v2.png"], actionItems: [ { id: "a3", text: "Prepare merch mockups", done: false } ], createdAt: d(-5) },
      { id: "n3", title: "Atlas weekly sync", clientId: "c4", body: "Content nearly finalized. Development kicks off next sprint.", attachments: [], actionItems: [ { id: "a4", text: "Confirm CMS choice", done: false } ], createdAt: d(-2) },
    ],
    events: [
      { id: "e1", title: "Stripe standup", type: "meeting", date: d(1), clientId: "c5" },
      { id: "e2", title: "Acme design review", type: "meeting", date: d(2), clientId: "c1" },
      { id: "e3", title: "INV-172 due", type: "invoice", date: d(9), clientId: "c2" },
      { id: "e4", title: "Stripe project deadline", type: "deadline", date: d(20), clientId: "c5" },
      { id: "e5", title: "Dashboard milestone", type: "milestone", date: d(6), clientId: "c5" },
      { id: "e6", title: "Atlas kickoff call", type: "meeting", date: d(4), clientId: "c4" },
      { id: "e7", title: "INV-174 due", type: "invoice", date: d(12), clientId: "c1" },
    ],
    activities: [
      { id: "ac1", type: "client", text: "New client: Atlas Corp", at: d(-2) },
      { id: "ac2", type: "invoice", text: "Invoice paid: Atlas Corp — $6,800", at: d(-1) },
      { id: "ac3", type: "quote", text: "Quote viewed: Pixel Perfect", at: d(-3) },
      { id: "ac4", type: "project", text: "Milestone completed: Webhooks (Stripe)", at: d(-4) },
      { id: "ac5", type: "lead", text: "New lead: Northwind Labs", at: d(-4) },
      { id: "ac6", type: "invoice", text: "Invoice overdue: Stripe — $4,200", at: d(-6) },
    ],
    notifications: [
      { id: "nt1", title: "Invoice overdue", body: "INV-130 for Stripe is 8 days overdue.", at: d(-1), read: false, kind: "warning" },
      { id: "nt2", title: "Payment received", body: "Atlas Corp paid INV-173 — $6,800.", at: d(-1), read: false, kind: "success" },
      { id: "nt3", title: "Meeting tomorrow", body: "Stripe standup at 10:00 AM.", at: d(-0.5), read: true, kind: "info" },
    ],
  };
}
